apiVersion: v1
kind: Namespace
metadata:
  name: modern-upo-sandbox
  labels:
    app.kubernetes.io/name: modern-upo
    app.kubernetes.io/part-of: modern-upo
    app.kubernetes.io/environment: sandbox
