apiVersion: v1
kind: Secret
metadata:
  name: sandbox-app-secret
type: Opaque
stringData:
  mysql-root-password: root_pass
  mysql-app-user: app
  mysql-app-password: app_pass
  jwt-secret: change-me-in-env
  rabbitmq-username: admin
  rabbitmq-password: admin123
  mongodb-root-username: admin
  mongodb-root-password: admin123
  notification-service-mongo-uri: mongodb://admin:admin123@mongodb:27017/admin?authSource=admin
