apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: modern-upo-prod
resources:
  - namespace.yaml
  - configmap-app.yaml
  - configmap-frontend.yaml
  - frontend.yaml
  - gateway.yaml
  - user-service.yaml
  - product-service.yaml
  - order-service.yaml
  - notification-service.yaml
  - ingress.yaml
  - hpa.yaml
