apiVersion: v1
kind: Secret
metadata:
  name: prod-app-secret
type: Opaque
stringData:
  mysql-app-user: app
  mysql-app-password: change-me
  jwt-secret: change-me
  rabbitmq-username: admin
  rabbitmq-password: change-me
  notification-service-mongo-uri: mongodb://admin:change-me@docdb.cluster-xxxxxxxxxx.us-east-1.docdb.amazonaws.com:27017/admin?authSource=admin&retryWrites=false
